version: '3.4'

services:
  app:
    build:
      context: .
      target: development
      args:
        DOCKER_USER: ${DOCKER_USER:-1000}
    user: ${DOCKER_USER:-1000}
    image: fundocker/ralph:development
    env_file:
      - .env
    environment:
      PYLINTHOME: /app/.pylint.d
    volumes:
      - .:/app
    depends_on:
      - elasticsearch
      - swift

  elasticsearch:
    image: elasticsearch:7.10.1
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
  
  swift:
    image: jeantil/openstack-swift-keystone-docker:pike
    ports:
      - "49177:8080"
      - "49178:35357"

  dockerize:
    image: jwilder/dockerize
